server:
  port: 8081

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: naikram
    url: jdbc:mysql://localhost:3306/School
    password: Mathematics100#
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: 'true'